# Secrets 模板
# 实际值通过 Devtron Dashboard 的 Secret Manager 或外部 Secret Store (Vault) 配置
# 此文件仅作为字段参考，不包含真实值
apiVersion: v1
kind: Secret
metadata:
  name: seed-secrets
type: Opaque
stringData:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: ""  # 通过 Devtron Secret Manager 设置
  REDIS_PASSWORD: ""     # 通过 Devtron Secret Manager 设置
  JWT_SECRET: ""          # 通过 Devtron Secret Manager 设置
